### ISSUE TITLE
0.7 Feature/Mechanic - To Do List

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#50]
MUST DO:
- [ ] Fix All Added Buildings
  - [ ] Garaz Mala
  - [ ] Schnell
  - [ ] Olenstivklkas;kanr
- [ ] Remove A2 Gas Stations and Pubs Use Fixed A1 ones
- [ ] Comment out Mag Crafting 
- [x] Add Required Magazines for Vilas
- [ ] Fix Machete
- [ ] Inventory Counters
- [x] RACS/SpecOps Clothing Lootable
- [ ] Fix Vehicle Speeds
- [ ] SkyBox
- [ ] New Textures

++++
Old 0.2.2 List
- [x] Make UI Streamer Friendly - Issue #25 
- [x] Move "Build Fireplace" to Woodpile not matches
- [x] Add Remaining Well types to drink from script
  - [ ] land_water_tank
  - [ ] land_water_tank2
  - [x] land_kasna
  - [ ] land_kasna_new
  - [ ] land_kasna_new_bez
  - [ ] land_kasna_sucha
  - [ ] land_pumpa
- [ ] Inventory Counters
- [ ] Add Short action animation for drinking from well
- [x] Allow Light fire if flares in inventory
- [ ] Add More Fueling Points (More above ground tanks)
- [x] Add Auto Refuel Option at Gas Stations Issue #70 
- [ ] Add refuel option to Green Mil Fuel Station Gas Tanks
- [x] Add Mi8 Crash type - Issue #5 
- [x] Reduce Audio range or volume of actions - Issue #18 
- [ ] Increase swimming speed
- [x] Add Smookies Lite animation lite pack
- [ ] Leave Combat loggers in game 1 min.
- [x] Slow/Reduced Blood Bagging + Self Blood bagging?
- [ ] Gather Wood Mechanic - produce woodpile by sitting in forest for 30seconds - Issue #19 
- [ ] force manual reloading of all vehicle weapons
- [ ] Remove default ammo from ALL vehicles - Issue #28 
- [ ] Reduce/Remove Armor and Damage points for Some Vehicles - Issue #6 
- [x] Make Ammo Cache Hold Less and Harder to  build
- [ ] Fix Drag Body Running
- [ ] Black out passout window leave just white timer
- [ ] Loot skins from dead players

**Comment by EHDSeven** [comment]
Moved a lot of the functions to long term since some need extra assets or will require quite a bit of time to create and debug

**Comment by NonovUrbizniz** [comment]
Have updated the list and moved a bunch to long term. Then moved a fair bit back, should be managable but maybe not feel free to move as many as needed back to long term. I am going to start sorting the lists and linking listed items to issues.
