### ISSUE TITLE
Long Term Mechanic List

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#52]
- [ ] When holy books are in junk loot, allow them to "absolve sins" to gain humanity if bandit.
- [ ] Make "pants" lootable for Sahrani civilians with both skins
- [ ] If Passed out access gear like dead body
- [ ] Group Mechanic giving Arm patches - default or custom
- [ ] Allow Friendly Fire Forgiveness once group mechanic is working
- [ ] Make Bolt Cutters Knock down a section of Fence OR spawn in a fence section with hole
- [ ] Live Heli Wrecks UH1 and Mi17
- [ ] Persistent bodies after restart (3 types Zed = Empty / Dead = corpse  Buried = Cross #48
- [ ] Armored Vehicles only on tank island
- [ ] Drop/Throw raw meat to distract/attract zombies zombies
- [ ] Force / default to lower weapon? 
- [ ] Pick Pocket Zombie (access gear menu while alive IF YOU CAN)
- [ ] Add Money to junk loot but make it burnable to cook meat/boil water
- [ ] Strip Music Completely, files and triggers/logic if it's big or complicated
- [ ] Shapoopy - Issue #68
- [ ] Make Balaclava lootable
- [ ] Make just Bandit mask Lootable
- [ ] Black out spawn in
- [ ] Unarmed Player kills don't lower humanity
- [ ] Allow to drag players with broken legs - Must be accepted
- [x] Cut Down Trees - Knock Down Tree With Axe, Harvest wood with Axe, Tree disappears - Issue #21 
- [ ]  Melee Weapons in Secondary Weapon Slot
- [x] Make Ammo Cache Hold Less and Harder to  build - More nails - Camo net - Issue #24 
- [ ] Make people gut/eatable?
- [ ] Add Smookies Lite animation pack modded
- [x] Slow/Reduced Blood Bagging + Self Bloodbagging?
- [ ] Give Vehicles Default Inventories - Issue #60 
- [ ] Add Cargo Lift Script - Issue #67 
- [ ] Allow 3rd Party Players to claim dead players tents, stashes, caches, buildings etc - Issue #23 
- [ ] Add Siphon Fuel from Vehicle Mechanic - Issue #70 
- [ ] Add Vehicle Part Harvesting
- [ ] Add Zone Specific Features Issue #69 
- [ ] Re Do Health System Issue #66

**Comment by Noxiousd** [comment]
to possibly save this, could just give the option to "Pray at altar" in churches, to remove some humanity
