### ISSUE TITLE
Code Lock - Lets get a 0.2.2 build out

### ISSUE THREAD

**Issue by NonovUrbizniz** [CiFor/DayZ_Sahrani#71]
MUST To Do List:
- [ ] SledgeHammer,Bolt Cutter, Axe Mechanic additions/changes - Issue #21 
- [ ] FIX Stop Air Vehicles spawning Zombies, Lower number spawned by cars? - Issue #34  
- [x] Add Auto Refuel Option at Gas Tanks and Gas Stations Issue #70 
- [x] Add More Fueling Points (More above ground tanks)?
- [ ] Switch Melee ALL Melee Weapons to secondary Weapon slot - Issue #22 
- [x] Include ra_chat_off.pbo and bisign http://forums.bistudio.com/showthread.php?120648-ANTI-Chat-(Disable-chat-ingame)
- [x] FIX - Make Refuel things - land_fuelstation_army land_fuelstation
- [ ] Fix Drag Body Running
- [ ] Black out passout window leave just white timer
- [ ] force manual reloading of all vehicle weapons
- [ ] Remove default ammo from ALL vehicles - Issue #28 
- [ ] Leave Combat loggers in game 1 min.
- [x] Slow/Reduced Blood Bagging + Self Blood bagging?
- [ ] Gather Wood Mechanic - produce woodpile by sitting in forest for 30seconds - Issue #19 
- [x] Loot skins from dead players
- [x] Add Mi8 Crash type - Issue #5 
- [x] Put in New Models
- [ ] Inventory Counters
- [ ] Increase swimming speed
- [ ] Knock Out Mechanic - Issue #80 

Good To Do:
- [ ] Active Heli Crashes - UH1Y + Mi8 + C130
- [ ] Active Cargo Drops - C130 dropping Food/Water/Industrial
- [ ] Texture interior of Hospital ?
- [ ] Add Smookies Lite animation lite pack
- [ ] Reduce/Remove Armor and Damage points for Some Vehicles - Issue #6 
- [ ] Increase View Distance? - Issue #12 

DONE:
- [x] Make UI Streamer Friendly - Issue #25 
- [x] Move "Build Fireplace" to Woodpile not matches - Issue #16 
- [x] Add Remaining Well types to drink from script - Issue #15 
- [x] Reduce Audio range or volume of actions - Issue #18 
- [x] Remove Lobby Menu
- [x] Last Green Menu Select highlight bar in "F" command menus
- [x] Make Ammo Cache Hold Less and Harder to  build - Issue #24 
- [x] Increase Nail/Sandbags spawns - Issue #61
- [x] Allow Light fire if flares in inventory - Issue #17
- [x] Create Garage Interior
- [x] Add Short action animation for drinking from well
- [x] Color change Gear UI - From Browns, yellows,, whites -> Black Translucent base Dark Grey Buttons, White Text, Light Grey item area (lighter grey when selected)
- [x] FIX No Inventory Clothes package when changing out of Bandit Ghillie (male or female) issue #59

**Comment by EHDSeven** [comment]
http://i.imgur.com/dMSNd2C.png
That building you ordered :+1:

**Comment by EHDSeven** [comment]
Working my way down the list done so far.
